version: '3.3'
services:
  webrtcstat_gatekeeper:
    container_name: docker_webrtcstat_gatekeeper
    image: webrtcstat:latest
    links:
      - kafka
    ports:
      - 8088:7080
    environment:
      - APPLICATION_SERVER_PORT=7080
      - KAFKA_HOSTS=docker_kafka:29092
      - GOOGLE_APPLICATION_CREDENTIALS=bg_credential.json
  zookeeper:
    container_name: docker_zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: docker_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://docker_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
