apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webrtc-observer.fullname" . }}-config
data:
  guestbook-name: {{ .Values.config.guestbook_name }}
  backend-uri: http://{{ .Release.Name}}.{{ .Values.config.backend_uri }}