---
micronaut:
  server:
    port: "${APPLICATION_SERVER_PORT:8088}"
  application:
    name: gatekeeper
    authentication:
      hashAlgorithm: "${AUTHENTICATION_HASH_ALGORITHM:`SHA-512`}"
      stretching: "${AUTHENTICATION_STRETCHING:2}"
      saltSize: "${AUTHENTICATION_SALT_SIZE:32}"
      
#  security:
#    enabled: true
#    endpoints:
#      login:
#        enabled: true
#      oauth:
#        enabled: true
#    token:
#      jwt:
#        enabled: true
#        signatures:
#          secret:
#            generator:
#              secret: jwtsecretforgatekeeperrandomchars1234543465434565
---
hikari:
  username:  "${HIKARI_MYSQL_USERNAME:root}"
  password: "${HIKARI_MYSQL_PASSWORD:password}"
  minIdleInMs: "${HIKARI_MYSQL_MIN_IDLE_IN_MS:100}"
  timeout: "${HIKARI_MYSQL_TIMEOUT_IN_MS:1000}"
  jdbc: "${HIKARI_JDBC:`jdbc:mysql://localhost:3306/ObserveRTC`}"
  maxPoolSize: "${HIKARI_MAX_POOL_SIZE:100}"
  poolname: "${HIKARI_POOL_NAME:gatekeeper}"

---
sink:
  builder: KafkaSinkBuilder
  configuration:
    hosts:
      - "localhost:9092"
    groupId: "myGroup"
#sink:
#  builder: ElasticsearchSink
#  configuration:

#datasources:
#  #  default:
#  #    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#  #    password: ${JDBC_PASSWORD:"password"}
#  #    url: ${JDBC_URL:`jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL`}
#  #    username: ${JDBC_USER:user}
#  default:
#    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/wobserver`}
#    username: ${JDBC_USER:root}
#    password: ${JDBC_PASSWORD:password}
#    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
#    dialect: MYSQL
---
isc:
  streams:
    demo:
      samples: "${ISC_STREAMS_DEMO_SAMPLES_TOPIC:demoSamples}"
---
kafka:
  bootstrap:
    servers: "${KAFKA_HOSTS:`localhost:9092`}"
  