micronaut:
  server:
    port: ${APPLICATION_SERVER_PORT:9888}
  application:
    name: WebRTC-BigQueryReporter
kafka:
  bootstrap:
    servers: localhost:9092


reporter:
  observeRTCReportsTopic: ${KAFKA_TOPICS_OBSERVERTC_REPORTS:observertcReports}
  projectName: ${REPORTSINK_BIGQUERY_PROJECT_NAME:observertc}
  datasetName: ${REPORTSINK_BIGQUERY_DATASET_NAME:WebRTC}
  createDatasetIfNotExists: ${REPORTSINK_BIGQUERY_CREATE_DATASET_IF_NOT_EXISTS:True}
  createTableIfNotExists: ${REPORTSINK_BIGQUERY_CREATE_TABLE_IF_NOT_EXISTS:True}
